import React from 'react';
import { Container, Card } from 'react-bootstrap';

const PrivacyPolicy: React.FC = () => {
  return (
    <Container className="mt-5 mb-5">
      <Card>
        <Card.Body>
          <div data-custom-class="body">
            <div><strong><span style={{ fontSize: '26px' }}><span data-custom-class="title"><h1>PRIVACY POLICY</h1></span></span></strong></div>
            <div><span style={{ color: 'rgb(127, 127, 127)' }}><strong><span style={{ fontSize: '15px' }}><span data-custom-class="subtitle">Last updated November 11, 2025</span></span></strong></span></div>
            <div><br /></div>
            <div><br /></div>
            <div><br /></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ color: 'rgb(127, 127, 127)' }}><span style={{ color: 'rgb(89, 89, 89)', fontSize: '15px' }}><span data-custom-class="body_text">This Privacy Notice for ACT Math Sprint ("<strong>we</strong>," "<strong>us</strong>," or "<strong>our</strong>"), describes how and why we might access, collect, store, use, and/or share ("<strong>process</strong>") your personal information when you use our services ("<strong>Services</strong>"), including when you:</span></span></span></div>
            <ul>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px', color: 'rgb(89, 89, 89)' }}><span><span data-custom-class="body_text">Visit our website at <span style={{ color: 'rgb(0, 58, 250)' }}><a href="https://actmathsprint.com" target="_blank" rel="noopener noreferrer" data-custom-class="link">https://actmathsprint.com</a></span>, or any website of ours that links to this privacy notice</span></span></span></li>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px', color: 'rgb(89, 89, 89)' }}><span data-custom-class="body_text">Engage with us in other related ways, including any sales, marketing, or events</span></span></li>
            </ul>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px', color: 'rgb(89, 89, 89)' }}><span data-custom-class="body_text">Read this privacy notice carefully as it will help you understand what we do with the information that we collect.</span></span></div>
            <div><br /></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="heading_1"><strong>TABLE OF CONTENTS</strong></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><a data-custom-class="link" href="#infocollect">1. WHAT INFORMATION DO WE COLLECT?</a></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><a data-custom-class="link" href="#infouse">2. HOW DO WE PROCESS YOUR INFORMATION?</a></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><a data-custom-class="link" href="#whoshare">3. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</a></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><a data-custom-class="link" href="#cookies">4. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</a></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><a data-custom-class="link" href="#inforetain">5. HOW LONG DO WE KEEP YOUR INFORMATION?</a></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><a data-custom-class="link" href="#infominors">6. DO WE COLLECT INFORMATION FROM MINORS?</a></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><a data-custom-class="link" href="#privacyrights">7. WHAT ARE YOUR PRIVACY RIGHTS?</a></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><a data-custom-class="link" href="#californiaprivacyrights">8. CALIFORNIA PRIVACY RIGHTS</a></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><a data-custom-class="link" href="#do-not-track">9. DO WE MAKE UPDATES TO THIS NOTICE?</a></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><a data-custom-class="link" href="#contact">10. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</a></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><a data-custom-class="link" href="#request">11. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</a></span></span></div>
            <div><br /></div>
            <div id="infocollect" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="heading_1"><strong>1. WHAT INFORMATION DO WE COLLECT?</strong></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="heading_2"><strong>Personal information you disclose to us</strong></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong><em>In Short:</em></strong><em> We collect personal information that you provide to us.</em></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">We collect personal information that you voluntarily provide to us when you register on the Services, express an interest in obtaining information about us or our products and Services, when you participate in activities on the Services (such as by posting messages in our online forums or entering competitions, contests, or giveaways) or otherwise when you contact us.</span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong>Personal Information Provided by You.</strong> The personal information that we collect depends on the context of your interactions with us and the Services, the choices you make and the products and features you use. The personal information we collect may include the following:</span></span></div>
            <ul>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">names</span></span></li>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">email addresses</span></span></li>
            </ul>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong>Sensitive Information.</strong> We do not process sensitive information.</span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong>Social Media Login Data.</strong> We may provide you with the option to register with us using your existing social media account details, like your Google, Facebook, or other social media account. If you choose to register in this way, we will collect the Information described in the section called "<a data-custom-class="link" href="#whoshare">HOW DO WE HANDLE YOUR SOCIAL LOGINS?</a>" below.</span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">All personal information that you provide to us must be true, complete, and accurate, and you must notify us of any changes to such personal information.</span></span></div>
            <div><br /></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="heading_2"><strong>Information automatically collected</strong></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong><em>In Short:</em></strong><em> Some information — such as your Internet Protocol (IP) address and/or browser and device characteristics — is collected automatically when you visit our Services.</em></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">We automatically collect certain information when you visit, use, or navigate the Services. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about how and when you use our Services, and other technical information. This information is primarily needed to maintain the security and operation of our Services, and for our internal analytics and reporting purposes.</span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">Like many businesses, we also collect information through cookies and similar technologies.</span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">The information we collect includes:</span></span></div>
            <ul>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><em>Log and Usage Data.</em> Log and usage data is service-related, diagnostic, usage, and performance information our servers automatically collect when you access or use our Services and which we record in log files. Depending on how you interact with us, this log data may include your IP address, device information, browser type, and settings and information about your activity in the Services (such as the date/time stamps associated with your usage, pages and files viewed, searches, and other actions you take), device event information (e.g., system activity, error reports (sometimes called "crash dumps")), and hardware settings.</span></span></li>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><em>Device Data.</em> We collect device data such as information about your computer, phone, tablet, or other device you use to access the Services. Depending on the device used, this device data may include information such as your IP address (or proxy server), device and application identification numbers, location, browser type, hardware model, Internet service provider and/or mobile carrier, operating system, and system configuration information.</span></span></li>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><em>Location Data.</em> We collect location data such as information about your device's location, which can be either precise or imprecise. How much information we collect depends on the type and settings of the device you use to access the Services. For example, we may use GPS and other technologies to collect geolocation data that tells us your current location (based on your IP address). You can opt out of allowing us to collect that information either by refusing access to the information or by disabling your Location setting on your device. However, if you choose to opt out, you may not be able to use certain aspects of the Services.</span></span></li>
            </ul>
            <div><br /></div>
            <div id="infouse" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="heading_1"><strong>2. HOW DO WE PROCESS YOUR INFORMATION?</strong></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong><em>In Short:</em></strong><em> We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent.</em></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong>We process your personal information for a variety of reasons, depending on how you interact with our Services, including:</strong></span></span></div>
            <ul>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong>To facilitate account creation and authentication and otherwise manage user accounts. </strong>We may process your information so you can create and log in to your account, as well as keep your account in working order.</span></span></li>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong>To deliver and facilitate delivery of services to the user.</strong> We may process your information to provide you with the requested service.</span></span></li>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong>To respond to user inquiries/offer support to users.</strong> We may process your information to respond to your inquiries and solve any potential issues you might have with the requested service.</span></span></li>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong>To send you marketing and promotional communications.</strong> We may process the personal information you send to us for our marketing purposes, if this is in accordance with your marketing preferences. You can opt out of our marketing emails at any time. For more information, see "<a data-custom-class="link" href="#privacyrights">WHAT ARE YOUR PRIVACY RIGHTS?</a>" below.</span></span></li>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong>To send administrative information to you. </strong>We may process your information to send you product, service, and new feature information and/or information about changes to our terms, conditions, and policies.</span></span></li>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong>To protect our Services.</strong> We may process your information as part of our efforts to keep our Services safe and secure, including fraud monitoring and prevention.</span></span></li>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong>To identify usage trends.</strong> We may process information about how you use our Services to better understand how they are being used so we can improve them.</span></span></li>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px', color: 'rgb(89, 89, 89)' }}><span data-custom-class="body_text"><strong>To save or protect an individual's vital interest.</strong> We may process your information when necessary to save or protect an individual’s vital interest, such as to prevent some harm.</span></span></li>
            </ul>
            <div><br /></div>
            <div id="whoshare" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="heading_1"><strong>3. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</strong></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong><em>In Short:</em></strong><em> We may share information in specific situations described in this section and/or with the following third parties.</em></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">We may need to share your personal information in the following situations:</span></span></div>
            <ul>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px', color: 'rgb(89, 89, 89)' }}><span data-custom-class="body_text"><strong>Business Transfers.</strong> We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.</span></span></li>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px', color: 'rgb(89, 89, 89)' }}><span data-custom-class="body_text"><strong>When we use Google Firebase platform.</strong> We may share your information with Google Firebase platform to provide you with the requested service.</span></span></li>
            </ul>
            <div><br /></div>
            <div id="cookies" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="heading_1"><strong>4. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</strong></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong><em>In Short:</em></strong><em> We may use cookies and other tracking technologies to collect and store your information.</em></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">We may use cookies and similar tracking technologies (like web beacons and pixels) to access or store information. Specific information about how we use such technologies and how you can refuse certain cookies is set out in our Cookie Notice.</span></span></div>
            <div><br /></div>
            <div id="inforetain" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="heading_1"><strong>5. HOW LONG DO WE KEEP YOUR INFORMATION?</strong></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong><em>In Short:</em></strong><em> We keep your information for as long as necessary to fulfill the purposes outlined in this privacy notice unless otherwise required by law.</em></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy notice, unless a longer retention period is required or permitted by law (such as tax, accounting, or other legal requirements). No purpose in this notice will require us keeping your personal information for longer than the period of time in which users have an account with us.</span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">When we have no ongoing legitimate business need to process your personal information, we will either delete or anonymize such information, or, if this is not possible (for example, because your personal information has been stored in backup archives), then we will securely store your personal information and isolate it from any further processing until deletion is possible.</span></span></div>
            <div><br /></div>
            <div id="infominors" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="heading_1"><strong>6. DO WE COLLECT INFORMATION FROM MINORS?</strong></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong><em>In Short:</em></strong><em> We do not knowingly collect data from or market to children under 18 years of age.</em></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">We do not knowingly solicit data from or market to children under 18 years of age. By using the Services, you represent that you are at least 18 or that you are the parent or guardian of such a minor and consent to such minor dependent’s use of the Services. If we learn that personal information from users less than 18 years of age has been collected, we will deactivate the account and take reasonable measures to promptly delete such data from our records. If you become aware of any data we may have collected from children under age 18, please contact us at __________.</span></span></div>
            <div><br /></div>
            <div id="privacyrights" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="heading_1"><strong>7. WHAT ARE YOUR PRIVACY RIGHTS?</strong></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong><em>In Short:</em></strong><em> You may review, change, or terminate your account at any time.</em></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">If you are located in the EEA or UK, and you believe we are unlawfully processing your personal information, you also have the right to complain to your local data protection supervisory authority. You can find their contact details here: <a data-custom-class="link" href="https://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm" target="_blank" rel="noopener noreferrer">https://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm</a>.</span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">If you are located in Switzerland, the contact details for the data protection authorities are available here: <a data-custom-class="link" href="https://www.edoeb.admin.ch/edoeb/en/home.html" target="_blank" rel="noopener noreferrer">https://www.edoeb.admin.ch/edoeb/en/home.html</a>.</span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong><u>Withdrawing your consent:</u></strong> If we are relying on your consent to process your personal information, which may be express and/or implied consent depending on the applicable law, you have the right to withdraw your consent at any time. You can withdraw your consent by contacting us by using the contact details provided in the section "<a data-custom-class="link" href="#contact">HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</a>" below.</span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">However, please note that this will not affect the lawfulness of the processing before its withdrawal nor, when applicable law allows, will it affect the processing of your personal information conducted in reliance on lawful processing grounds other than consent.</span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong><u>Account Information:</u></strong> If you would at any time like to review or change the information in your account or terminate your account, you can:</span></span></div>
            <ul>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px', color: 'rgb(89, 89, 89)' }}><span data-custom-class="body_text">Log in to your account settings and update your user account.</span></span></li>
              <li data-custom-class="body_text" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px', color: 'rgb(89, 89, 89)' }}><span data-custom-class="body_text">Contact us using the provided contact information.</span></span></li>
            </ul>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">Upon your request to terminate your account, we will deactivate or delete your account and information from our active databases. However, we may retain some information in our files to prevent fraud, troubleshoot problems, assist with any investigations, enforce our Legal Terms and/or comply with applicable legal requirements.</span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">If you have questions or comments about your privacy rights, you may email us at __________.</span></span></div>
            <div><br /></div>
            <div id="californiaprivacyrights" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="heading_1"><strong>8. CALIFORNIA PRIVACY RIGHTS</strong></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text"><strong><em>In Short:</em></strong><em> If you are a resident of California, you are granted specific rights regarding access to your personal information.</em></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">California Civil Code Section 1798.83, also known as the "Shine The Light" law, permits our users who are California residents to request and obtain from us, once a year and free of charge, information about categories of personal information (if any) we disclosed to third parties for direct marketing purposes and the names and addresses of all third parties with which we shared personal information in the immediately preceding calendar year. If you are a California resident and would like to make such a request, please submit your request in writing to us using the contact information provided below.</span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">If you are under 18 years of age, reside in California, and have a registered account with the Services, you have the right to request removal of unwanted data that you publicly post on the Services. To request removal of such data, please contact us using the contact information provided below, and include the email address associated with your account and a statement that you reside in California. We will make sure the data is not publicly displayed on the Services, but please be aware that the data may not be completely or comprehensively removed from all our systems (e.g., backups, etc.).</span></span></div>
            <div><br /></div>
            <div id="do-not-track" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="heading_1"><strong>9. DO WE MAKE UPDATES TO THIS NOTICE?</strong></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '1.5' }}><span data-custom-class="body_text"><strong><em>In Short:</em></strong><em> Yes, we will update this notice as necessary to stay compliant with relevant laws.</em></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">We may update this privacy notice from time to time. The updated version will be indicated by an updated "Revised" date and the updated version will be effective as soon as it is accessible. If we make material changes to this privacy notice, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this privacy notice frequently to be informed of how we are protecting your information.</span></span></div>
            <div><br /></div>
            <div id="contact" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="heading_1"><strong>10. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</strong></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">If you have questions or comments about this notice, you may email us at <a href="mailto:support@actmathsprint.com" data-custom-class="link">support@actmathsprint.com</a>.</span></span></div>
            <div><br /></div>
            <div id="request" style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="heading_1"><strong>11. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</strong></span></span></div>
            <div style={{ lineHeight: '1.5' }}><span style={{ fontSize: '15px' }}><span data-custom-class="body_text">Based on the applicable laws of your country, you may have the right to request access to the personal information we collect from you, change that information, or delete it in some circumstances. To request to review, update, or delete your personal information, please visit: <a href="https://actmathsprint.com/settings" target="_blank" rel="noopener noreferrer" data-custom-class="link">https://actmathsprint.com/settings</a>.</span></span></div>
            <div><br /></div>
          </div>
        </Card.Body>
      </Card>
    </Container>
  );
};

export default PrivacyPolicy;